ApptiveDev/ygyg-be

- src/main/java/foiegras/ygyg/global/common/security/CustomUserDetails.java
- src/main/java/foiegras/ygyg/global/config/security/SecurityConfig.java
- src/main/java/foiegras/ygyg/post/api/controller/PostController.java
- src/main/java/foiegras/ygyg/post/api/request/CreateUserPostRequest.java
- src/main/java/foiegras/ygyg/post/application/dto/in/CreateUserPostInDto.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/UserPostEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/UserPostJpaRepository.java
- src/main/java/foiegras/ygyg/user/api/controller/AuthController.java
- src/main/java/foiegras/ygyg/user/api/request/SingUpRequest.java
- src/main/java/foiegras/ygyg/user/api/response/SignUpResponse.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SiginInOutDto.java
- src/main/java/foiegras/ygyg/user/application/dto/out/SignUpOutDto.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
- 레이어드 아키텍쳐 기본적인 구조 설정
- global, user, post 생성
- 프로젝트 구조
> feat: 레이어드 아키텍쳐 프로젝트 구조 설정

- src/main/java/foiegras/ygyg/user/infrastructure/entity/JoinRouteEntity.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/enums/UserRole.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/JoinRouteJpaRepository.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
- #6
- UserEntity 생성
- JoinRouteEntity 생성
- 각각 JpaRepository 생성
> [#6]feat: 유저, 서비스 알게된 경로 entity 생성 및 JpaRepository 생성

- src/main/java/foiegras/ygyg/user/api/controller/EmailController.java
- src/main/java/foiegras/ygyg/user/api/response/CheckEmailDuplicateResponse.java
- src/main/java/foiegras/ygyg/user/application/dto/out/CheckEmailDuplicateOutDto.java
- src/main/java/foiegras/ygyg/user/application/service/EmailService.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
- #6 
- 이메일 중복확인 api 구현
- DB에서 유저가 입력한 이메일에 해당하는 유저가 있는지 확인하여 중복확인 진행 
- 중복확인 결과:
> [#6]feat: 이메일 중복 확인 api 개발

- src/main/java/foiegras/ygyg/global/common/security/CustomAccessDeniedHandler.java
- src/main/java/foiegras/ygyg/global/common/security/CustomAuthenticationEntryPoint.java
- src/main/java/foiegras/ygyg/global/common/security/CustomUserDetails.java
- src/main/java/foiegras/ygyg/global/common/security/CustomUserDetailsService.java
- src/main/java/foiegras/ygyg/global/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/foiegras/ygyg/global/common/security/jwt/JwtTokenProvider.java
- src/main/java/foiegras/ygyg/global/config/security/CorsConfig.java
- src/main/java/foiegras/ygyg/global/config/security/SecurityAppConfig.java
- src/main/java/foiegras/ygyg/global/config/security/SecurityConfig.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
> [#6]feat: security & jwt 설정

- src/main/java/foiegras/ygyg/global/config/security/SecurityConfig.java
- src/main/java/foiegras/ygyg/user/api/controller/AuthController.java
- src/main/java/foiegras/ygyg/user/api/request/SignInRequest.java
- src/main/java/foiegras/ygyg/user/api/response/SignInResponse.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SignInInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/out/SignInOutDto.java
- src/main/java/foiegras/ygyg/user/application/facade/SignInFacade.java
- src/main/java/foiegras/ygyg/user/application/facade/SignUpFacade.java
- src/main/java/foiegras/ygyg/user/application/service/AuthService.java
- src/main/java/foiegras/ygyg/user/application/service/UserService.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
- #6 
- 로그인 API 구현에 필요한 Controller, Facade, DTO Class 생성
- 로그인id/pw를 입력받아 유저 조회 후 인증 진행, 토큰 생성하는 로직 구현
- SecurityConfig: 로그인 API 경로를 인증 예외처리
> feat: 로그인 API 구현

- .github/workflows/gradle-prod.yml
- ci/cd를 위한 github actions workflow 파일 작성
> infra: github actions workflow 작성

- .github/workflows/gradle-prod.yml
ygyg[v1.0.0-beta.2]
- github actions에서 build시에 test를 실행하다보니 해당하는 yml이 없어서 빌드 실패
- 따라서 -x test 옵션을 추가하여 테스트 없이 빌드하도록 수정
> Hotfix:v1.0.0-beta.2

- Dockerfile
- docker로 build하기 위해 dockerfile 생성
> infra: dockerfile 생성

- Dockerfile
ygyg[v1.0.0-beta.3]
- docker로 build하기 위해 dockerfile 생성
> Release:v1.0.0-beta.3

- src/main/java/foiegras/ygyg/global/config/security/SecurityConfig.java
- src/main/java/foiegras/ygyg/user/api/controller/EmailController.java
- src/main/java/foiegras/ygyg/user/api/request/VerifyAuthCodeRequest.java
- src/main/java/foiegras/ygyg/user/api/response/VerifyAuthCodeResponse.java
- src/main/java/foiegras/ygyg/user/application/dto/in/VerifyAuthCodeInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/out/VerifyAuthCodeOutDto.java
- src/main/java/foiegras/ygyg/user/application/service/AuthEmailService.java
- 인증 코드 확인에 필요한 Controller, Service, DTO 구현
- 인증에 성공하면 redis에서 key를 삭제, 실패하면 그대로 둠
> feat: 인증 코드 확인 api 구현

- src/main/java/foiegras/ygyg/user/api/request/SignInRequest.java
- src/main/java/foiegras/ygyg/user/api/request/SignUpRequest.java
- src/main/java/foiegras/ygyg/user/application/dto/in/CreateUserInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SignInInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SignUpInDto.java
- src/main/java/foiegras/ygyg/user/application/facade/SignInFacade.java
- src/main/java/foiegras/ygyg/user/application/facade/SignUpFacade.java
- src/main/java/foiegras/ygyg/user/application/service/AuthService.java
- src/main/java/foiegras/ygyg/user/application/service/UserService.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
- 정책상 유저 이메일을 아이디로 대체
- 따라서 해당 필드를 사용하는 부분을 모두 삭제 및 UserEmail로 대체
- 로그인/회원가입 Controller, Service, Dto, Request 등등
- 로그인시 UserEmail을 사용!!
> modify: UserSignInId를 UserEmail로 대체

- build.gradle
- src/main/java/foiegras/ygyg/global/common/redis/RedisUtil.java
- src/main/java/foiegras/ygyg/global/config/redis/RedisConfig.java
- src/main/java/foiegras/ygyg/global/config/security/SecurityConfig.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/ParticipatingUsersEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/UserPostEntity.java
- src/main/java/foiegras/ygyg/user/api/controller/EmailController.java
- src/main/java/foiegras/ygyg/user/api/request/SendAuthenticationEmailRequest.java
- src/main/java/foiegras/ygyg/user/api/request/SignInRequest.java
- src/main/java/foiegras/ygyg/user/api/request/SignUpRequest.java
- src/main/java/foiegras/ygyg/user/api/request/VerifyAuthCodeRequest.java
- src/main/java/foiegras/ygyg/user/api/response/VerifyAuthCodeResponse.java
- src/main/java/foiegras/ygyg/user/application/dto/in/CreateUserInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SendAuthenticationEmailInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SignInInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SignUpInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/in/VerifyAuthCodeInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/out/SendEmailOutDto.java
- src/main/java/foiegras/ygyg/user/application/dto/out/VerifyAuthCodeOutDto.java
- src/main/java/foiegras/ygyg/user/application/facade/SendAuthEmailFacade.java
- src/main/java/foiegras/ygyg/user/application/facade/SignInFacade.java
- src/main/java/foiegras/ygyg/user/application/facade/SignUpFacade.java
- src/main/java/foiegras/ygyg/user/application/service/AuthEmailService.java
- src/main/java/foiegras/ygyg/user/application/service/AuthService.java
- src/main/java/foiegras/ygyg/user/application/service/EmailService.java
- src/main/java/foiegras/ygyg/user/application/service/UserService.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
ygyg[v1.0.0-beta.3]
- 참여자 테이블 생성
- 정책상 로그인Id 대신 email을 Id로 사용하기로 결정. 따라서 UserSignInId를 UserEmail로 대체
- API 구현
- 인증 메일 전송 api
- 인증 코드 확인 api
> Release:v1.0.0-beta.4

- src/main/java/foiegras/ygyg/user/api/request/SignUpRequest.java
- src/main/java/foiegras/ygyg/user/application/dto/in/CreateUserInDto.java
- src/main/java/foiegras/ygyg/user/application/dto/in/SignUpInDto.java
- src/main/java/foiegras/ygyg/user/application/facade/SignUpFacade.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- #6 
- request, dto, entity에서 'userName' 필드 추가
> fix: UserEntity에서 누락된 필드 추가

- src/main/java/foiegras/ygyg/user/api/response/SignInResponse.java
- src/main/java/foiegras/ygyg/user/application/dto/out/SignInOutDto.java
- src/main/java/foiegras/ygyg/user/application/facade/SignInFacade.java
- src/main/java/foiegras/ygyg/user/application/service/AuthService.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- #6 
- 로그인 response에 'userName', 'userEmail' 필드 추가
- UserEntity에서 정적 팩토리 메서드에서 누락된 필드 추가
> modify: 로그인 response 수정

- src/main/java/foiegras/ygyg/comment/api/controller/CommentController.java
- src/main/java/foiegras/ygyg/comment/api/request/CreateCommentRequest.java
- src/main/java/foiegras/ygyg/comment/application/dto/in/CreateCommentInDto.java
- src/main/java/foiegras/ygyg/comment/application/port/CommentRepository.java
- src/main/java/foiegras/ygyg/comment/application/service/CommentService.java
- src/main/java/foiegras/ygyg/comment/domain/model/Comment.java
- src/main/java/foiegras/ygyg/comment/infrastructure/CommentRepositoryImpl.java
- src/main/java/foiegras/ygyg/comment/infrastructure/entity/CommentEntity.java
- src/main/java/foiegras/ygyg/comment/infrastructure/jpa/CommentJpaRepository.java
- src/main/java/foiegras/ygyg/global/common/response/BaseResponseStatus.java
- #29 
- domain model & persistence model 기타 도메인 패키지를 hexagonal 구조로 생성
- 댓글 작성에 필요한 controller & service & repository 생성
- UserPostId를 받아서 댓글 생성
> feat: 댓글 작성 api 개발

- .github/workflows/gradle-prod.yml
- Dockerfile
- Dockerfile 및 Workflow에서 버전 명시 및 최적화, 최신화 진행
> infra: dockerfile, workflow 수정

- Dockerfile
> fix: Dockerfile 잘못된 경로 수정

- Dockerfile
ygyg[v1.0.0-beta.7]
- Dockerfile의 실행 스테이지에서 잘못된 경로를 수정
> Hotfix:v1.0.0-beta.7

- Dockerfile
> fix: Dockerfile 잘못된 경로 수정(2)

- Dockerfile
ygyg[v1.0.0-beta.8]
- Dockerfile에서 ENTRYPOINT의 잘못된 경로 수정
> Hotfix:v1.0.0-beta.8

- src/main/java/foiegras/ygyg/global/common/response/BaseResponseStatus.java
- src/main/java/foiegras/ygyg/post/api/controller/PostController.java
- src/main/java/foiegras/ygyg/post/api/request/CreatePostRequest.java
- src/main/java/foiegras/ygyg/post/application/dto/in/CreatePostInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/PostDataInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/UserPostDataInDto.java
- src/main/java/foiegras/ygyg/post/application/service/PostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/ItemPortioningUnitEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/PostEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/SeasoningCategoryEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/UserPostEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/ItemImageUrlJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/ItemPortioningUnitJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/ParticipatingUsersJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/PostJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/SeasoningCategoryJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/UserPostJpaRepository.java
- 엔티티별 repository 생성
- request dto인 CreatePostRequest, indto인 CreatePostInDto 생성
- PostController 생성
- PostService 생성 -> 엔티티별 매핑은 빌더패턴 사용
1. 저장되는 uuid가 binary(16) 규격에 초과되는 버그 => mariaDB 버전문제
2. container가 실행이 안되는 문제 => docker-compose.yml에 database명, mariadb admin password 명시 제대로
3. request json이 @RequestBody reqDTO에 매핑이 하나도 안돼 속성이 null로만 들어간 버그 => Jackson이 reqDTO의 생성자 혹은 getter/setter을 사용하기 때문에 reqDTO 엔티티에 @NoArgsConstructor 붙여줘야함
커밋양이 좀 많은데 단순 변수명 변경이나 잡다한것도 포함돼있어 feat 접두사 붙은거 위주로 봐주시면 좀 나을 것 같습니다!
<br>
> feat: createPost 구현

- src/main/java/foiegras/ygyg/global/common/response/BaseResponseStatus.java
- src/main/java/foiegras/ygyg/post/api/controller/PostController.java
- src/main/java/foiegras/ygyg/post/api/request/CreatePostRequest.java
- src/main/java/foiegras/ygyg/post/api/response/GetPostResponse.java
- src/main/java/foiegras/ygyg/post/application/dto/in/CreatePostInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/GetPostInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/GetPostOutDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/PostDataInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/PostDataOutDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/UserPostDataInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/in/UserPostDataOutDto.java
- src/main/java/foiegras/ygyg/post/application/service/PostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/ItemPortioningUnitEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/PostEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/SeasoningCategoryEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/UserPostEntity.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/ItemImageUrlJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/ItemPortioningUnitJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/ParticipatingUsersJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/PostJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/SeasoningCategoryJpaRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/UserPostJpaRepository.java
ygyg[v1.0.0-beta.9]
- API 개발
- 게시글 작성 API
- 게시글 상세조회 API
> Release:v1.0.0-beta.9

- src/main/java/foiegras/ygyg/user/api/controller/AuthController.java
- src/main/java/foiegras/ygyg/user/api/request/SignUpRequest.java
- src/main/java/foiegras/ygyg/user/application/dto/in/DeleteAccountInDto.java
- src/main/java/foiegras/ygyg/user/application/service/AuthService.java
- src/main/java/foiegras/ygyg/user/infrastructure/entity/UserEntity.java
- src/main/java/foiegras/ygyg/user/infrastructure/jpa/UserJpaRepository.java
- #6 
- 회원 탈퇴시 더이상 유저의 nickname 정보가 필요하지 않기에 hardDelete 처리
> feat: 회원탈퇴 API 개발

- src/main/java/foiegras/ygyg/post/application/service/ParticipatingUserService.java
> fix: import 주소 잘못된 부분 수정

- build.gradle
- src/main/java/foiegras/ygyg/global/common/interceptor/ApiLogInterceptor.java
- src/main/java/foiegras/ygyg/global/common/response/BaseResponseStatus.java
- src/main/java/foiegras/ygyg/global/common/wrapper/CachingRequestWrapper.java
- src/main/java/foiegras/ygyg/global/config/interceptor/WebMvcConfig.java
- #4 
- 모니터링을 위해 모든 api 요청시 log를 남겨주는 interceptor를 구현
- 이를 위해 request를 캐싱한 CachingRequestWrapper 구현 및 관련된 의존성 추가
> feat: api interceptor 구현

- src/main/java/foiegras/ygyg/global/common/security/jwt/JwtAuthenticationFilter.java
- #6 
- request에서 정보를 읽어올 때, caching request를 사용하여 정보를 가져옴으로써, 여러 번 읽어들일 수 있도록 수정
> fix: CachingRequest 사용하도록 JwtFilter 수정

- src/main/java/foiegras/ygyg/global/common/security/jwt/JwtAuthenticationFilter.java
ygyg[v1.0.0-beta.13]
- request를 캐싱하여, request를 읽어오는 부분에서 발생하는 i/o exception 수정
> Hotfix:v1.0.0-beta.13

- build.gradle
- src/main/java/foiegras/ygyg/aws/api/controller/AwsController.java
- src/main/java/foiegras/ygyg/aws/api/request/GetPutObjectPreSignedUrlRequest.java
- src/main/java/foiegras/ygyg/aws/api/response/GetPreSignedUrlResponse.java
- src/main/java/foiegras/ygyg/aws/application/dto/in/GetPutObjectPreSignedUrlInDto.java
- src/main/java/foiegras/ygyg/aws/application/dto/out/GetPutObjectPreSignedUrlOutDto.java
- src/main/java/foiegras/ygyg/aws/application/service/AwsService.java
- src/main/java/foiegras/ygyg/global/S3Config.java
- #10 
- aws 의존성 추가
- accessKeyId와 secretKey를 사용하여 presigner 구현 & putObjectPresignedUrl 생성
> feat: aws s3 파일 업로드를 위한 presignedUrl 생성 API 개발

- .github/workflows/gradle-prod.yml
- #26 
- 모든 환경변수를 build시에 application-prod.yml으로 주입하던 기존 방법에서, 아주 중요한 환경변수는 런타임시에 주입하도록 변경
> infra: github actions workflow 파일 환경변수 주입 방법 수정

- .github/workflows/gradle-prod.yml
> fix: 환경변수 주입 에러 수정

- .github/workflows/gradle-prod.yml
ygyg[v1.0.0-beta.16]
- 환경변수 주입 에러 수정
> Hotfix:v1.0.0-beta.16

- src/main/java/foiegras/ygyg/global/common/querydsl/PostDomainQueryDslUtil.java
- src/main/java/foiegras/ygyg/global/config/security/SecurityConfig.java
- src/main/java/foiegras/ygyg/post/api/controller/UserPostController.java
- src/main/java/foiegras/ygyg/post/application/dto/userpost/in/SearchPostInDto.java
- src/main/java/foiegras/ygyg/post/application/service/UserPostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/querydsl/UserPostQueryDslRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/querydsl/UserPostQueryDslRepositoryImpl.java
- #10 
- keyword로 제목 검색 API 개발
- 정렬 기준은 latest, soonest, lowestPrice, lowestRemain 총 4가지 존재
- isMinimumPeopleMet으로 최소기준 달성여부를 추가 조회할 수 있음
- securityConfig에 로그인 없이 접근할 수 있도록 등록
> feat: 게시글 검색 API 개발

- src/main/java/foiegras/ygyg/global/common/querydsl/PostDomainQueryDslUtil.java
- src/main/java/foiegras/ygyg/global/config/security/SecurityConfig.java
- src/main/java/foiegras/ygyg/post/api/controller/UserPostController.java
- src/main/java/foiegras/ygyg/post/application/dto/userpost/in/SearchPostInDto.java
- src/main/java/foiegras/ygyg/post/application/service/UserPostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/querydsl/UserPostQueryDslRepository.java
- src/main/java/foiegras/ygyg/post/infrastructure/querydsl/UserPostQueryDslRepositoryImpl.java
ygyg[v1.0.0-beta.17]
- 게시글 검색 API 개발
> Release:v1.0.0-beta.17

- src/main/java/foiegras/ygyg/post/api/controller/UserPostController.java
- src/main/java/foiegras/ygyg/post/application/dto/userpost/in/GetUserPostListByCategoryInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/userpost/in/GetUserPostListInDto.java
- src/main/java/foiegras/ygyg/post/application/service/UserPostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/post/UserPostJpaRepository.java
#58 
- 최소소분인원이 충족된 게시글만 볼 수 있는 기능 추가
<br>
> feat: 소분글 목록 api에 최소소분인원 게시글 필터링

- src/main/java/foiegras/ygyg/aws/api/controller/AwsController.java
- src/main/java/foiegras/ygyg/aws/application/service/AwsService.java
- Issue
- #10 
- key('유저email-fileName')를 사용해서 s3에서 이미지 삭제
> feat: s3 이미지 삭제 API 개발

- src/main/java/foiegras/ygyg/aws/api/controller/AwsController.java
- src/main/java/foiegras/ygyg/aws/application/service/AwsService.java
- src/main/java/foiegras/ygyg/post/api/controller/UserPostController.java
- src/main/java/foiegras/ygyg/post/application/dto/userpost/in/GetUserPostListByCategoryInDto.java
- src/main/java/foiegras/ygyg/post/application/dto/userpost/in/GetUserPostListInDto.java
- src/main/java/foiegras/ygyg/post/application/service/UserPostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/post/UserPostJpaRepository.java
ygyg[v1.0.0-beta.18]
- s3 이미지 삭제 API 개발
- 소분글 목록 조회 API에서, 최소 소분인원 달성 필터링 기능 추가
> Release:v1.0.0-beta.18

- src/main/java/foiegras/ygyg/YgygApplication.java
- src/main/java/foiegras/ygyg/global/common/schedulers/ExpiredPostsDeleteScheduler.java
- src/main/java/foiegras/ygyg/post/application/service/PostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/jpa/post/UserPostJpaRepository.java
- nativeQuery로 소분일시+1일 && 최소소분인원 미충족 게시글 불러옴
- n시 0분 0초에 자동삭제 스케쥴링
로직 실행은 어느정도로 해야할지 잘 몰라서 일단 보수적으로 매 시각 정각으로 정했습니다.
<br>
> feat: 미성사 소분글 자동 삭제 스케쥴링 기능 개발

- src/main/java/foiegras/ygyg/global/event/DeleteAccountEventHandler.java
- src/main/java/foiegras/ygyg/post/api/controller/PostController.java
- src/main/java/foiegras/ygyg/post/api/response/CreatePostResponse.java
- src/main/java/foiegras/ygyg/post/application/dto/post/out/CreatePostOutDto.java
- src/main/java/foiegras/ygyg/post/application/facade/JoinPortioningFacade.java
- src/main/java/foiegras/ygyg/post/application/service/PostService.java
- src/main/java/foiegras/ygyg/post/application/service/UserPostService.java
- src/main/java/foiegras/ygyg/post/infrastructure/entity/UserPostEntity.java
- 최대인원-현인원 => 최소인원-현인원
- 소분글 게시/수정 서비스 코드 이에 맞춰 변경
- userPostEntity 자체의 updateRemainCount 메서드에 업데이트 조건문 명시
<br>
> modify: remainCount을 최소소분인원 충족까지 남은 카운트로 수정
